name: API Jest Test using Git Pipelines
on:
  schedule:
    - cron: '30 6 * * *'
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Set timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')"
      - name: Create test-results directories
        run: |
          mkdir -p ./test-results/api-test-results
      - name: Install dependencies
        run: npm install
      - name: Run API tests
        run: jest --config=jest.config.js
      - name: Debug - List files in test-results
        run: ls -R ./test-results
      - name: Upload API Test Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: api-test-report-${TIMESTAMP}
          path: ./test-results/api-test-results
          retention-days: 30
